version: '3'
services:
  client:
    platform: linux/x86_64
    build: .
    environment:
      SERVER_DOMAIN: 0.0.0.0:8000
      NUXT_PUBLIC_TYPEWRITER: false
    ports:
      - '${CLIENT_PORT:-80}:80'
    networks:
      - chatgpt_ui_network
    restart: always

networks:
  chatgpt_ui_network:
    name: chatgpt_ui_network
    driver: bridge
    external: true
